# Maven

# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - main

pool:
  vmImage: macos latest

steps:

  - script: |
      echo %LT_BUILD_NAME%   
      wget https://downloads.lambdatest.com/concierge/darwin/concierge 
      chmod u+x concierge
      chmod u+x concierge
      
      ./concierge -u  meerap -k I9ADikrjXtd5i0yOXOtjmRQRSpcA5ng6PxIvHwEuWvNtQ8CTWd -i hyperexecuteStatic.yaml



  - script: |
      echo "Test"